# Generated by Django 3.2.19 on 2023-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sector', models.CharField(choices=[('commercial', 'Commercial'), ('charity', 'Charity')], max_length=20)),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employer_name', models.CharField(max_length=100)),
                ('incorporation_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField()),
                ('expiry_date', models.DateField()),
                ('application_url', models.URLField()),
            ],
        ),
    ]
