# Generated by Django 3.2.19 on 2023-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("voluntary", "Voluntary (Unpaid)"),
                    ("temporary", "Temporary"),
                    ("fixed_term_contract", "Fixed Term Contract"),
                    ("part_time_permanent", "Part-time Permanent Employed"),
                    ("full_time_permanent", "Full-time Permanent Employed"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
