# Generated by Django 3.2.19 on 2023-06-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_auto_20230610_0901"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
