# Generated by Django 3.2.19 on 2023-06-26 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
