# Generated by Django 3.2.19 on 2023-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='published_date',
        ),
        migrations.AddField(
            model_name='job',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
