# Generated by Django 3.2.22 on 2023-10-08 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20230626_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='incorporation_number',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
