version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - celery_worker

  celery_worker:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: celery
    command: celery -A web worker -l INFO # If logging level omitted, default is "warning"
    environment: 
      - DEBUG=0 #If DEBUG enabled, Celery warns about the risk of memory leaks. In production change to "DEBUG=0"
    depends_on:
      - rabbitmq
    restart: 'no'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: geekzone-rabbit
    ports:
      - "15672:15672"
