version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - celery_worker

  celery_worker:
    build: .
    command: celery -A memberships worker -l info
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes:
      - .:/code

  rabbitmq:
    image: rabbitmq:3-management
    hostname: geekzone-rabbit
    ports:
      - "15672:15672"
