version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: django-backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file: 
      - web/.env
    ports:
      - "8000:8000"
    depends_on:
      - celery_worker

  celery_worker:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: celery
    command: celery -A web worker -l INFO # If logging level omitted, default is "warning"
    env_file: 
      - web/.env
    depends_on:
      - rabbitmq
    restart: 'no'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: geekzone-rabbit
    user: rabbitmq
    ports:
      - "15672:15672"
    
  
