#!/usr/bin/env bash

PR_NUMBER=$(echo ${CIRCLE_PULL_REQUEST##*/})
TOTAL_FILES=$(curl -s -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/GeekZoneHQ/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER}/files | jq '.[] | {filename} | values[]' | wc -l)
echo "The number of committed files in this PR is $TOTAL_FILES"
MD_FILES=$(curl -s -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/GeekZoneHQ/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER}/files | jq '.[] | {filename} | values[]' | grep .md | wc -l)
echo "The number of modified or added markdown files in this PR is $MD_FILES"
changes=`git show --name-only ${CIRCLE_SHA1} | tail -n +7`
if [ $MD_FILES -eq $TOTAL_FILES ] || [ "$changes" = ".circleci/config.yml" ]; then
  echo "Skip ci"
  circleci-agent step halt
fi