#!/bin/bash -e

PR_NUMBER=$(echo ${CIRCLE_PULL_REQUEST##*/})
changes=$(curl -s -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/GeekZoneHQ/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER}/files | jq '.[] | {filename} | values[]' | wc -l)
echo "The number of committed files in this PR is $changes"
md_files=$(curl -s -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/GeekZoneHQ/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER}/files | jq '.[] | {filename} | values[]' | grep .md | wc -l)
echo "The number of markdown files in this PR is $md_files"

if [ ${md_files} -eq ${changes} ]; then
  echo "Skip ci"
  circleci-agent step halt
fi