# Generated by Django 3.0.7 on 2020-11-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0004_auto_20200807_1947"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address_1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address line one"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="address_postcode",
            field=models.CharField(blank=True, max_length=10, verbose_name="Postcode"),
        ),
        migrations.AddField(
            model_name="member",
            name="gdpr_email_notifications",
            field=models.BooleanField(
                default=False,
                help_text="May we send you system notifications by email? This is required to participate in Geek.Zone Elections",
                verbose_name="Email notifications",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gdpr_email_updates",
            field=models.BooleanField(
                default=False,
                help_text="May we send you updates, like event information, via email?",
                verbose_name="Email updates",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gdpr_likeness",
            field=models.BooleanField(
                default=False,
                help_text="May we use photos, videos or voice recordings of you in our publications?",
                verbose_name="Likeness",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gdpr_post_notifications",
            field=models.BooleanField(
                default=False,
                help_text="May we send you system notifications by post? This includes 2FA and voting notifications",
                verbose_name="Post notifications",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gdpr_post_updates",
            field=models.BooleanField(
                default=False,
                help_text="May we send you updates, like event information, via post?",
                verbose_name="Post updates",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gdpr_sms_notifications",
            field=models.BooleanField(
                default=False,
                help_text="May we send you system notifications by SMS? This includes 2FA notifications",
                verbose_name="SMS notifications",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gdpr_sms_updates",
            field=models.BooleanField(
                default=False,
                help_text="May we sent you updates, like event information, via SMS?",
                verbose_name="SMS updates",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gdpr_telephone_notifications",
            field=models.BooleanField(
                default=False,
                help_text="May we call you to notify you of system messages? This includes 2FA",
                verbose_name="Phone notifications",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gdpr_telephone_updates",
            field=models.BooleanField(
                default=False,
                help_text="May we call you with updates, like event information?",
                verbose_name="Phone updates",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gift_aid",
            field=models.BooleanField(
                default=False,
                help_text="I would like The UK Government to increase the value of my donation by as much as 25% at no cost to me!<br /><br />I want to Gift Aid my donation, and any donations I make in the future or have made in the past 4 years, to Geek.Zone. I am a UK taxpayer and understand that if I pay less Income Tax and/or Capital Gains Tax than the amount of Gift Aid claimed on all my donations in that tax year it is my responsibility to pay any difference.<br /><br />I will notify Geek.Zone if I:<ul><li>want to cancel this declaration</li><li>change my name or home address</li><li>no longer pay sufficient tax on my income and/or capital gains</li></ul>",
                verbose_name="Gift aid",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="minecraft_username",
            field=models.CharField(
                blank=True,
                help_text="What is your Minecraft Java Edition username? Let us know so that you can join us on Geek.Zone/Minecraft!",
                max_length=255,
                verbose_name="Minecraft username",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Strike a geek pose and give us your best shot! This will be used on your GZID card",
                upload_to="images/",
                verbose_name="Selfie",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.DateField(
                help_text="When did you begin your glorious adventure around or local star?",
                verbose_name="Date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="constitution_agreed",
            field=models.BooleanField(
                help_text='I have read and agree to abide by the <a href="http://geek.zone/constitution">Geek.Zone/Constitution</a>.'
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Full name"),
        ),
        migrations.AlterField(
            model_name="member",
            name="preferred_name",
            field=models.CharField(
                help_text="What should we call you?",
                max_length=255,
                verbose_name="Preferred name",
            ),
        ),
    ]
