# Generated by Django 3.0.7 on 2020-12-29 22:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_auto_20201120_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.Member')),
            ],
        ),
    ]
