# Generated by Django 3.1.6 on 2021-02-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0007_auto_20210125_0057"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="renewal_date",
            field=models.DateTimeField(
                null=True, verbose_name="Membership renewal date"
            ),
        ),
    ]
