# Generated by Django 3.1.7 on 2021-03-30 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0009_auto_20210323_1611"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="profile_image",
        ),
    ]
