# Generated by Django 3.1.7 on 2021-04-13 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0011_auto_20210330_2019"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={
                "permissions": (
                    ("has_membership", "Member has paid"),
                    (
                        "reminder_email_24hr",
                        "New member sent 24hr payment email",
                    ),
                    (
                        "reminder_email_72hr",
                        "New member sent 72hr payment email",
                    ),
                ),
                "verbose_name": "member",
                "verbose_name_plural": "members",
            },
        ),
    ]
