# Generated by Django 3.1.7 on 2021-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0011_auto_20210330_2019"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Email verified"),
        ),
    ]
