# Generated by Django 3.1.7 on 2021-04-21 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0012_member_email_verified"),
        ("memberships", "0013_membership_payment_status"),
    ]

    operations = []
