name: Eisenhower
on:
  issues:
    types: [opened, reopened, edited]
jobs:
  prioritise:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GH_REPOSITORY: ${{ github.repository }}
      GH_ISSUE_NUMBER: ${{ github.event.issue.number }}
    steps:
    - name: Run Eisenhower action
      uses: GeekZoneHQ/eisenhower@main
